export const accountTranslations = {
    'en': {
        'ACCOUNT_LOADING': 'Account loading',
        'ACCOUNT_NOT_FOUND': 'Account wasn\'t found',
        'ACCOUNT_FULL_NAME': 'Full name',
        'ACCOUNT_FULL_NAME_REQUIRED': 'Name is required',
        'ACCOUNT_POSITION': 'Position',
        'ACCOUNT_COMPANY': 'Company',
        'ACCOUNT_EMAIL': 'Email',
        'ACCOUNT_EMAIL_REQUIRED': 'Email is required',
        'ACCOUNT_EMAIL_REGEX': 'Bad email address',
        'ACCOUNT_CHANGE_PASSWORD': 'Change password',
        'ACCOUNT_LANGUAGE': 'Language',
        'ACCOUNT_LANGUAGE_EN': 'English',
        'ACCOUNT_LANGUAGE_RU': 'Russian',
        'ACCOUNT_THEME': 'Theme',
        'ACCOUNT_THEME_PIPLIGHTTHEME': 'Light',
        'ACCOUNT_THEME_PIPDARKTHEME': 'Dark',
        'ACCOUNT_THEME_PIPMONOTHEME': 'Monochrome',
        'ACCOUNT_MENU_MODE': 'Navigation',
        'ACCOUNT_MENU_MODE_FAVORITES': 'Default (favorites only)',
        'ACCOUNT_MENU_MODE_ALL': 'All applications in groups',
        'ACCOUNT_APPLY': 'Apply',
        'ACCOUNT_CANCEL': 'Cancel',
    },
    'ru': {
        'ACCOUNT_LOADING': 'Загрузка профиля',
        'ACCOUNT_NOT_FOUND': 'Профиль не найден',
        'ACCOUNT_FULL_NAME': 'Полное имя',
        'ACCOUNT_FULL_NAME_REQUIRED': 'Поле обязательно',
        'ACCOUNT_POSITION': 'Должность',
        'ACCOUNT_COMPANY': 'Компания',
        'ACCOUNT_EMAIL': 'Email',
        'ACCOUNT_EMAIL_REQUIRED': 'Поле обязательно',
        'ACCOUNT_EMAIL_REGEX': 'Неверное значение',
        'ACCOUNT_CHANGE_PASSWORD': 'Изменить пароль',
        'ACCOUNT_LANGUAGE': 'Язык',
        'ACCOUNT_LANGUAGE_EN': 'Английский',
        'ACCOUNT_LANGUAGE_RU': 'Русский',
        'ACCOUNT_THEME': 'Тема',
        'ACCOUNT_THEME_PIPLIGHTTHEME': 'Светлая',
        'ACCOUNT_THEME_PIPDARKTHEME': 'Темная',
        'ACCOUNT_THEME_PIPMONOTHEME': 'Монохромная',
        'ACCOUNT_MENU_MODE': 'Навигация',
        'ACCOUNT_MENU_MODE_FAVORITES': 'Стандартная (только избранное)',
        'ACCOUNT_MENU_MODE_ALL': 'Все приложения по группам',
        'ACCOUNT_APPLY': 'Применить',
        'ACCOUNT_CANCEL': 'Отменить',
    }
};
